In [1]:
import pandas as pd

In [4]:
pd.Series([43,22,63,41,35])

0    43
1    22
2    63
3    41
4    35
dtype: int64

In [5]:
seri = pd.Series([43,22,63,41,35])

In [6]:
type(seri)

pandas.core.series.Series

In [7]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [8]:
seri.dtype

dtype('int64')

In [9]:
seri.size

5

In [10]:
seri.ndim

1

In [11]:
seri.values

array([43, 22, 63, 41, 35])

In [12]:
seri.head()

0    43
1    22
2    63
3    41
4    35
dtype: int64

In [13]:
seri.head(3)

0    43
1    22
2    63
dtype: int64

In [14]:
seri.tail(3)

2    63
3    41
4    35
dtype: int64

In [16]:
import numpy as np

In [17]:
a = np.array([1,23,31,45,15])

In [18]:
seri = pd.Series(a)

In [19]:
seri

0     1
1    23
2    31
3    45
4    15
dtype: int64

In [20]:
seri[0]

1

In [21]:
seri[0:4]

0     1
1    23
2    31
3    45
dtype: int64

In [22]:
seri = pd.Series([122,200,150,99], index= ["reg","loj","cart","rf"])

In [23]:
seri

reg     122
loj     200
cart    150
rf       99
dtype: int64

In [24]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [25]:
seri.keys

<bound method Series.keys of reg     122
loj     200
cart    150
rf       99
dtype: int64>

In [27]:
list(seri.items())

[('reg', 122), ('loj', 200), ('cart', 150), ('rf', 99)]

In [29]:
seri.values

array([122, 200, 150,  99])

In [28]:
"reg" in seri

True

In [30]:
"a" in seri

False

In [31]:
seri["reg"]

122

In [32]:
seri[["rf","reg"]]

rf      99
reg    122
dtype: int64

In [33]:
seri["reg"] = 130

In [34]:
seri["reg"]

130

In [35]:
seri

reg     130
loj     200
cart    150
rf       99
dtype: int64

In [37]:
seri["reg":"cart"]

reg     130
loj     200
cart    150
dtype: int64

In [38]:
l = [1,2,39,67,90]

In [39]:
l

[1, 2, 39, 67, 90]

In [42]:
pd.DataFrame(l,columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [43]:
m = np.arange(1,10).reshape((3,3))

In [45]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
pd.DataFrame(m,columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [47]:
df = pd.DataFrame(m,columns = ["var1","var2","var3"])

In [48]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [50]:
df.columns = ("deg1","deg2","deg3")

In [52]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [53]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [54]:
df.shape

(3, 3)

In [55]:
df.size

9

In [56]:
df.ndim

2

In [60]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
type(df.values)

numpy.ndarray

In [62]:
type(df)

pandas.core.frame.DataFrame

In [67]:
df.head(2)

deg1  deg2  deg3
0     1     2     3
1     4     5     6

In [65]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [68]:
a = np.array([1,2,3,4,5])

In [69]:
pd.DataFrame(a, columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

In [70]:
s1 = np.random.randint(10, size=5)

In [73]:
s1

array([9, 9, 3, 2, 2])

In [71]:
s2 = np.random.randint(10, size=5)

In [74]:
s2

array([9, 2, 0, 0, 6])

In [72]:
s3 = np.random.randint(10, size=5)

In [75]:
s3

array([1, 3, 0, 3, 4])

In [78]:
sozluk = {"var1":s1,"var2":s2,"var3":s3}

In [79]:
sozluk

{'var1': array([9, 9, 3, 2, 2]),
 'var2': array([9, 2, 0, 0, 6]),
 'var3': array([1, 3, 0, 3, 4])}

In [80]:
df = pd.DataFrame(sozluk)

In [81]:
df

var1  var2  var3
0     9     9     1
1     9     2     3
2     3     0     0
3     2     0     3
4     2     6     4

In [82]:
df[0:1]

var1  var2  var3
0     9     9     1

In [84]:
df[1:3]

var1  var2  var3
1     9     2     3
2     3     0     0

In [85]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [86]:
df.index = ["a","b","c","d","e"]

In [87]:
df

var1  var2  var3
a     9     9     1
b     9     2     3
c     3     0     0
d     2     0     3
e     2     6     4

In [89]:
df["c":"e"]

var1  var2  var3
c     3     0     0
d     2     0     3
e     2     6     4

In [90]:
df.drop("a", axis = 0)

var1  var2  var3
b     9     2     3
c     3     0     0
d     2     0     3
e     2     6     4

In [91]:
df

var1  var2  var3
a     9     9     1
b     9     2     3
c     3     0     0
d     2     0     3
e     2     6     4

In [92]:
df.drop("a", axis = 0, inplace = True)

In [93]:
df

var1  var2  var3
b     9     2     3
c     3     0     0
d     2     0     3
e     2     6     4

In [94]:
l = ["c","e"]

In [95]:
df.drop(l,axis=0)

var1  var2  var3
b     9     2     3
d     2     0     3

In [96]:
"var1" in df

True

In [97]:
l = ["var1","var4","var2"]

In [99]:
for i in l:
    print(i in df)

True
False
True


In [100]:
df

var1  var2  var3
b     9     2     3
c     3     0     0
d     2     0     3
e     2     6     4

In [102]:
df["var1"]

b    9
c    3
d    2
e    2
Name: var1, dtype: int64

In [103]:
df["var4"] = df["var1"]/df["var2"]

In [104]:
df

var1  var2  var3      var4
b     9     2     3  4.500000
c     3     0     0       inf
d     2     0     3       inf
e     2     6     4  0.333333

In [107]:
df.drop("var4",axis=1)

var1  var2  var3
b     9     2     3
c     3     0     0
d     2     0     3
e     2     6     4

In [106]:
df

var1  var2  var3      var4
b     9     2     3  4.500000
c     3     0     0       inf
d     2     0     3       inf
e     2     6     4  0.333333

In [108]:
df.drop("var4",axis=1,inplace = True)

In [109]:
df

var1  var2  var3
b     9     2     3
c     3     0     0
d     2     0     3
e     2     6     4

In [113]:
l = ["var1","var3"]

In [114]:
df.drop(l,axis=1)

var2
b     2
c     0
d     0
e     6

In [115]:
m = np.random.randint(1,30,size=(10,3))

In [116]:
df = pd.DataFrame(m,columns = ["var1","var2","var3"])
df

var1  var2  var3
0    23    11     2
1    16    27     5
2     8     1     1
3    19    18    28
4     2    27     8
5     4     8    15
6    21    12     8
7    25     5    19
8    29    17    24
9    12    20     2

In [120]:
#loc: tanimlandigi sekli ile secim yapmak icin

In [118]:
df.loc[0:3]

var1  var2  var3
0    23    11     2
1    16    27     5
2     8     1     1
3    19    18    28

In [119]:
#iloc: alisik oldugumuz indeksleme mantigiyla secim yapar

In [121]:
df.iloc[0:3]

var1  var2  var3
0    23    11     2
1    16    27     5
2     8     1     1

In [122]:
df.iloc[0,0]

23

In [123]:
df.iloc[:3,:2]

var1  var2
0    23    11
1    16    27
2     8     1

In [124]:
df.loc[0:3,"var3"]

0     2
1     5
2     1
3    28
Name: var3, dtype: int64

In [125]:
m = np.random.randint(1,30,size=(10,3))
df = pd.DataFrame(m,columns = ["var1","var2","var3"])
df

var1  var2  var3
0    22     7    29
1     4    15     7
2    27    20    18
3    14     2    22
4    17     2    19
5    28     4    20
6     6    23     7
7    27    16     3
8    26     7    22
9     5    11    22

In [126]:
df["var1"]

0    22
1     4
2    27
3    14
4    17
5    28
6     6
7    27
8    26
9     5
Name: var1, dtype: int64

In [127]:
df[0:2]["var2"]

0     7
1    15
Name: var2, dtype: int64

In [129]:
df[0:2][["var2","var3"]]

var2  var3
0     7    29
1    15     7

In [134]:
df[df.var1>15]

var1  var2  var3
0    22     7    29
2    27    20    18
4    17     2    19
5    28     4    20
7    27    16     3
8    26     7    22

In [135]:
df[(df.var1>15)&(df.var3<5)]

var1  var2  var3
7    27    16     3

In [137]:
df.loc[(df.var1>15),["var1","var2"]]

var1  var2
0    22     7
2    27    20
4    17     2
5    28     4
7    27    16
8    26     7

In [140]:
df[df.var1>15][["var1","var2"]]

var1  var2
0    22     7
2    27    20
4    17     2
5    28     4
7    27    16
8    26     7

In [143]:
m = np.random.randint(1,30,size=(5,3))
df1 = pd.DataFrame(m,columns = ["var1","var2","var3"])
df1

var1  var2  var3
0    21    13    26
1    24    18     7
2     1    22    26
3     9    17     9
4    19     4    13

In [145]:
df2 = df1 + 99
df2

var1  var2  var3
0   120   112   125
1   123   117   106
2   100   121   125
3   108   116   108
4   118   103   112

In [147]:
pd.concat([df1,df2])

var1  var2  var3
0    21    13    26
1    24    18     7
2     1    22    26
3     9    17     9
4    19     4    13
0   120   112   125
1   123   117   106
2   100   121   125
3   108   116   108
4   118   103   112

In [148]:
pd.concat([df1,df2], ignore_index = True)

var1  var2  var3
0    21    13    26
1    24    18     7
2     1    22    26
3     9    17     9
4    19     4    13
5   120   112   125
6   123   117   106
7   100   121   125
8   108   116   108
9   118   103   112

In [151]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [153]:
df2.columns = ["var1","var2","deg3"]

In [154]:
df2

var1  var2  deg3
0   120   112   125
1   123   117   106
2   100   121   125
3   108   116   108
4   118   103   112

In [157]:
pd.concat([df1,df2],ignore_index=True)

var1  var2  var3   deg3
0    21    13  26.0    NaN
1    24    18   7.0    NaN
2     1    22  26.0    NaN
3     9    17   9.0    NaN
4    19     4  13.0    NaN
5   120   112   NaN  125.0
6   123   117   NaN  106.0
7   100   121   NaN  125.0
8   108   116   NaN  108.0
9   118   103   NaN  112.0

In [158]:
pd.concat([df1,df2],ignore_index=True,join = "inner")

var1  var2
0    21    13
1    24    18
2     1    22
3     9    17
4    19     4
5   120   112
6   123   117
7   100   121
8   108   116
9   118   103

In [163]:
#birebir birlestirme

In [161]:
df1 = pd.DataFrame({'calisanlar':['Ali','Veli','Ayse','Fatma'],'grup':['Muhasebe','Muhendis','Muhendis','IK']})
df1

calisanlar      grup
0        Ali  Muhasebe
1       Veli  Muhendis
2       Ayse  Muhendis
3      Fatma        IK

In [162]:
df2 = pd.DataFrame({'calisanlar':['Ayse','Ali','Veli','Fatma'],'ilk_giris':['2010','2009','2014','2019']})
df2

calisanlar ilk_giris
0       Ayse      2010
1        Ali      2009
2       Veli      2014
3      Fatma      2019

In [164]:
pd.merge(df1,df2)

calisanlar      grup ilk_giris
0        Ali  Muhasebe      2009
1       Veli  Muhendis      2014
2       Ayse  Muhendis      2010
3      Fatma        IK      2019

In [165]:
pd.merge(df1,df2,on = 'calisanlar')

calisanlar      grup ilk_giris
0        Ali  Muhasebe      2009
1       Veli  Muhendis      2014
2       Ayse  Muhendis      2010
3      Fatma        IK      2019

In [166]:
#coktan teke birlestirme

In [168]:
df3 = pd.merge(df1,df2)
df3

calisanlar      grup ilk_giris
0        Ali  Muhasebe      2009
1       Veli  Muhendis      2014
2       Ayse  Muhendis      2010
3      Fatma        IK      2019

In [169]:
df4 = pd.DataFrame({'grup':['Muhasebe','Muhendis','IK'],'mudur':['Caner','Mustafa','Berkcan']})
df4

grup    mudur
0  Muhasebe    Caner
1  Muhendis  Mustafa
2        IK  Berkcan

In [170]:
pd.merge(df3,df4)

calisanlar      grup ilk_giris    mudur
0        Ali  Muhasebe      2009    Caner
1       Veli  Muhendis      2014  Mustafa
2       Ayse  Muhendis      2010  Mustafa
3      Fatma        IK      2019  Berkcan

In [171]:
#coktan coka birlestirme

In [172]:
df5 = pd.DataFrame({'grup':['Muhasebe','Muhasebe','Muhendis','Muhendis','IK','IK'],'yetenekler':['matematik','excel','kodlama','linux','excel','yonetim']})
df5

grup yetenekler
0  Muhasebe  matematik
1  Muhasebe      excel
2  Muhendis    kodlama
3  Muhendis      linux
4        IK      excel
5        IK    yonetim

In [173]:
pd.merge(df1,df5)

calisanlar      grup yetenekler
0        Ali  Muhasebe  matematik
1        Ali  Muhasebe      excel
2       Veli  Muhendis    kodlama
3       Veli  Muhendis      linux
4       Ayse  Muhendis    kodlama
5       Ayse  Muhendis      linux
6      Fatma        IK      excel
7      Fatma        IK    yonetim

In [174]:
import seaborn as sns

In [176]:
df = sns.load_dataset("planets")
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [177]:
df.shape

(1035, 6)

In [179]:
df["mass"].mean()

2.6381605847953233

In [180]:
df["mass"].count()

513

In [181]:
df["mass"].min()

0.0036

In [183]:
df["mass"].max()

25.0

In [184]:
df["mass"].sum()

1353.37638

In [185]:
df["mass"].var()

14.58183312700122

In [189]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [190]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

In [199]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],'veri':[10,11,52,23,43,55]},columns =['gruplar','veri'])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [200]:
df.groupby('gruplar')

In [201]:
df.groupby('gruplar').mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [204]:
df = sns.load_dataset('planets')
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [205]:
df.groupby("method")

In [206]:
df.groupby("method")["orbital_period"]

In [207]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [211]:
df.groupby("method")["orbital_period"].describe().T

method   Astrometry  Eclipse Timing Variations        Imaging  Microlensing  \
count      2.000000                   9.000000      12.000000      7.000000   
mean     631.180000                4751.644444  118247.737500   3153.571429   
std      544.217663                2499.130945  213978.177277   1113.166333   
min      246.360000                1916.250000    4639.150000   1825.000000   
25%      438.770000                2900.000000    8343.900000   2375.000000   
50%      631.180000                4343.500000   27500.000000   3300.000000   
75%      823.590000                5767.000000   94250.000000   3550.000000   
max     1016.000000               10220.000000  730000.000000   5100.000000   

method  Orbital Brightness Modulation  Pulsar Timing  \
count                        3.000000       5.000000   
mean                         0.709307    7343.021201   
std                          0.725493   16313.265573   
min                          0.240104       0.090706   
25%                          0.291496      25.262000   
50%                          0.342887      66.541900   
75%                          0.943908      98.211400   
max                          1.544929   36525.000000   

method  Pulsation Timing Variations  Radial Velocity     Transit  \
count                           1.0        553.00000  397.000000   
mean                         1170.0        823.35468   21.102073   
std                             NaN       1454.92621   46.185893   
min                          1170.0          0.73654    0.355000   
25%                          1170.0         38.02100    3.160630   
50%                          1170.0        360.20000    5.714932   
75%                          1170.0        982.00000   16.145700   
max                          1170.0      17337.50000  331.600590   

method  Transit Timing Variations  
count                    3.000000  
mean                    79.783500  
std                     71.599884  
min                     22.339500  
25%                     39.675250  
50%                     57.011000  
75%                    108.505500  
max                    160.000000

In [213]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],'degisken1':[10,23,33,22,11,99],
                   'degisken2':[100,253,333,262,111,969]},columns = ['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [219]:
#aggregate

In [216]:
df.groupby('gruplar').mean()

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [218]:
df.groupby('gruplar').aggregate(['min',np.median,max])

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   16.0  22       100  181.0  262
B              11   17.0  23       111  182.0  253
C              33   66.0  99       333  651.0  969

In [220]:
df.groupby('gruplar').aggregate({'degisken1':"min",'degisken2':"max"})

degisken1  degisken2
gruplar                      
A               10        262
B               11        253
C               33        969

In [221]:
#filter

In [222]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],'degisken1':[10,23,33,22,11,99],
                   'degisken2':[100,253,333,262,111,969]},columns = ['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [228]:
def filter_func(x):
    return x["degisken1"].std() > 9

In [230]:
df.groupby('gruplar').std()

degisken1   degisken2
gruplar                       
A         8.485281  114.551299
B         8.485281  100.409163
C        46.669048  449.719913

In [229]:
df.groupby('gruplar').filter(filter_func)

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

In [231]:
#transform

In [247]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],'degisken1':[10,23,33,22,11,99],
                   'degisken2':[100,253,333,262,111,969]},columns = ['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [233]:
df["degisken1"]*9

0     90
1    207
2    297
3    198
4     99
5    891
Name: degisken1, dtype: int64

In [238]:
df_a = df.iloc[:,1:3]

In [241]:
df_a.transform(lambda x: (x-x.mean())/x.std())

degisken1  degisken2
0  -0.687871  -0.738461
1  -0.299074  -0.263736
2   0.000000  -0.015514
3  -0.328982  -0.235811
4  -0.657963  -0.704331
5   1.973890   1.957853

In [242]:
#apply

In [244]:
df = pd.DataFrame({'degisken1':[10,23,33,22,11,99],
                   'degisken2':[100,253,333,262,111,969]},columns = ['degisken1','degisken2'])
df

degisken1  degisken2
0         10        100
1         23        253
2         33        333
3         22        262
4         11        111
5         99        969

In [245]:
df.apply(np.sum)

degisken1     198
degisken2    2028
dtype: int64

In [246]:
df.apply(np.mean)

degisken1     33.0
degisken2    338.0
dtype: float64

In [248]:
df.groupby('gruplar').apply(np.sum)

gruplar  degisken1  degisken2
gruplar                              
A            AA         32        362
B            BB         34        364
C            CC        132       1302

In [251]:
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [252]:
titanic.groupby('sex')['survived'].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [253]:
titanic.groupby('sex')[['survived']].mean()

survived
sex             
female  0.742038
male    0.188908

In [254]:
titanic.groupby(['sex','class'])[['survived']].aggregate('mean').unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [255]:
titanic.groupby(['sex','class'])[['survived']].aggregate('mean')

survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [256]:
#pivot ile table

In [257]:
titanic.pivot_table("survived",index = 'sex',columns='class')

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [258]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [262]:
age = pd.cut(titanic["age"],[0,18,90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [263]:
titanic.pivot_table("survived",["sex",age],"class")

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

In [264]:
#dis kaynakli veri okumak

In [268]:
#csv okuma
pd.read_csv('reading_data/ornekcsv.csv', sep = ";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [270]:
#txt okuma
pd.read_csv('reading_data/duz_metin.txt')

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [271]:
pd.read_excel('reading_data/ornekx.xlsx')

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [272]:
df = pd.read_excel('reading_data/ornekx.xlsx')

In [273]:
type(df)

pandas.core.frame.DataFrame