In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]
b = [2,3,4,5]

In [3]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [5]:
a*b

array([ 2,  6, 12, 20])

In [6]:
b = np.random.randint(10, size = (3,5))

In [7]:
b

array([[1, 7, 4, 8, 8],
       [0, 1, 9, 6, 6],
       [8, 4, 3, 0, 9]])

In [8]:
b.ndim

2

In [9]:
b.shape

(3, 5)

In [10]:
b.size

15

In [11]:
b.dtype

dtype('int64')

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [18]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [20]:
z = np.array([7,8,9])

In [21]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a = np.array([[1,2,3],
              [4,5,6]])

In [23]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [25]:
np.concatenate([a,a], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [26]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [27]:
x = np.array([1,2,3,99,99,3,2,1])

In [30]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [31]:
a,b,c = np.split(x,[3,5])

In [32]:
a

array([1, 2, 3])

In [33]:
b

array([99, 99])

In [34]:
c

array([3, 2, 1])

In [35]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [37]:
u,a = np.vsplit(m,[2])

In [38]:
u

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [39]:
a

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [42]:
l,r = np.hsplit(m,[2])

In [43]:
l

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [44]:
r

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [45]:
v = np.array([2,1,4,3,5])

In [46]:
v

array([2, 1, 4, 3, 5])

In [47]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [50]:
v.sort()

In [51]:
v

array([1, 2, 3, 4, 5])

In [53]:
f = np.random.normal(20,5,(3,3))

In [54]:
f

array([[16.86617947, 24.74683912, 21.16342317],
       [22.55182826, 17.72458326, 23.09115571],
       [19.78043015, 18.99435014, 16.15338897]])

In [55]:
np.sort(f, axis = 1)

array([[16.86617947, 21.16342317, 24.74683912],
       [17.72458326, 22.55182826, 23.09115571],
       [16.15338897, 18.99435014, 19.78043015]])

In [56]:
np.sort(f, axis = 0)

array([[16.86617947, 17.72458326, 16.15338897],
       [19.78043015, 18.99435014, 21.16342317],
       [22.55182826, 24.74683912, 23.09115571]])

In [58]:
m = np.random.randint(10, size= (5,5))

In [59]:
m

array([[7, 7, 2, 7, 9],
       [2, 8, 0, 1, 3],
       [6, 5, 1, 3, 4],
       [2, 3, 1, 0, 6],
       [4, 5, 3, 7, 9]])

In [60]:
m[:,0]

array([7, 2, 6, 2, 4])

In [61]:
m[:,1]

array([7, 8, 5, 3, 5])

In [62]:
m[:,0:2]

array([[7, 7],
       [2, 8],
       [6, 5],
       [2, 3],
       [4, 5]])

In [63]:
m[0:2,0:2]

array([[7, 7],
       [2, 8]])

In [64]:
a = np.random.randint(10, size=(5,5))
a

array([[0, 4, 6, 4, 5],
       [7, 3, 5, 9, 6],
       [2, 0, 6, 0, 9],
       [9, 1, 5, 1, 7],
       [1, 8, 7, 2, 2]])

In [65]:
alt_a = a[0:3,0:2]

In [66]:
alt_a

array([[0, 4],
       [7, 3],
       [2, 0]])

In [71]:
alt_a[0,0] = 99999
alt_a[1,1] = 88888

In [72]:
alt_a

array([[99999,     4],
       [    7, 88888],
       [    2,     0]])

In [73]:
a

array([[99999,     4,     6,     4,     5],
       [    7, 88888,     5,     9,     6],
       [    2,     0,     6,     0,     9],
       [    9,     1,     5,     1,     7],
       [    1,     8,     7,     2,     2]])

In [74]:
m = np.random.randint(10, size=(5,5))
m

array([[6, 7, 2, 8, 1],
       [0, 3, 3, 4, 6],
       [9, 7, 4, 6, 9],
       [6, 8, 8, 1, 2],
       [3, 1, 3, 4, 6]])

In [75]:
alt_m = m[0:3,0:2].copy()
alt_m

array([[6, 7],
       [0, 3],
       [9, 7]])

In [76]:
alt_m[0,0] = 99999
alt_m

array([[99999,     7],
       [    0,     3],
       [    9,     7]])

In [77]:
m

array([[6, 7, 2, 8, 1],
       [0, 3, 3, 4, 6],
       [9, 7, 4, 6, 9],
       [6, 8, 8, 1, 2],
       [3, 1, 3, 4, 6]])

In [78]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [79]:
v[1]

3

In [80]:
v[3]

9

In [81]:
v[5]

15

In [82]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [83]:
al_getir = [1,3,5]

In [84]:
v[al_getir]

array([ 3,  9, 15])

In [85]:
m = np.arange(9).reshape((3,3))

In [86]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
satir = np.array([0,1])

In [88]:
sutun = np.array([1,2])

In [89]:
m[satir,sutun]

array([1, 5])

5*x0+x1=12
x0+3*x1=10

In [91]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [92]:
a

array([[5, 1],
       [1, 3]])

In [93]:
b

array([12, 10])

In [94]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])